### PR TITLE
contrib: update libbpf to 0.6.1

### PR DESCRIPTION
**Pull request by fntlnz**
Updating libbpf to 0.6.1 as its needed for the new features being developed in current main and in #47 .

I separated the commit with all the steps involved to make it easier to understand what is happenign here.

Most of the patching we needed to do is now gone because the features we needed have been upstreamed.

The only missing thing is the fix that @stanek-michal did with the maps closing. Michal, I feel I would like to encourage you to upstream that change, thank you 😍 

To avoid any possible confusion I pushed the diff to my own libbpf fork so we can visualize what happens better

- Our changes on top of 0.6.1 https://github.com/libbpf/libbpf/compare/v0.6.1...fntlnz:el-bpf-0.6.1
- Our changes on top of the version we are having now in main  767d82c https://github.com/libbpf/libbpf/compare/767d82c...fntlnz:el-bpf-767d82c 

Supersedes #37

### CODE REVIEW

**Comment by fntlnz** [comment]
This is not working, investigating 🔍

**Comment by stanek-michal** [comment]
> The only missing thing is the fix that @stanek-michal did with the maps closing. Michal, I feel I would like to encourage you to upstream that change, thank you 😍

Thanks for reminding me, I'll get on it!

> This is not working, investigating 🔍
I think this removed the extra headers we copied in to get ARM64 to compile and to get it all to work with elftoolchain

**Comment by fntlnz** [comment]
ah you are correct @stanek-michal - I'll fix immediately, my `diff` didn't see it for some reason

**Comment by fntlnz** [comment]
oh yes yes @stanek-michal 

image

**Comment by fntlnz** [comment]
@stanek-michal , just added the headers PTAL

**Comment by fntlnz** [comment]
Looks like just copying the headers is not enough, investigating 🔬

**Comment by fntlnz** [comment]
Ok everything works now. Triggering CI to make sure tests pass as well.

**Comment by fntlnz** [comment]
Looks like CI does not have the latest version of the toolchain available.

**Comment by fntlnz** [comment]
I gave it a try and pushed a Jenkinsfile change (originally written by Michal) to download the new toolchain temporarly. We can remove that once build nodes are updated. I'll run jenkins now.

**Review by stanek-michal — APPROVED** [review]
Looks good, thanks! I only wonder about elfdefinitions.h but maybe it's not required with the new toolchain. I also added a commit here which handles the return value of set_kversion as the upstream version of that function returns int and our previous one was void.

**Review by leodido — APPROVED** [review]
LGTM even tho I would prefer to use git submodules

**Comment by fntlnz** [comment]
Thanks for the reviews @stanek-michal and @leodido - really appreciated.

I'll do some more checks and will merge this soon.

**Comment by mmat11** [comment]
@stanek-michal FYI, the fd leak should now be fixed in libbpf, don't know in which version will be released though

https://lore.kernel.org/bpf/164787600977.20941.4773407661485029217.git-patchwork-notify@kernel.org/T/#t

**Comment by stanek-michal** [comment]
> @stanek-michal FYI, the fd leak should now be fixed in libbpf, don't know in which version will be released though
> 
> https://lore.kernel.org/bpf/164787600977.20941.4773407661485029217.git-patchwork-notify@kernel.org/T/#t

Awesome, let's keep an eye on libbpf releases so we can pull the new version and remove our patch commits.

**Pull request merged**
