### PR TITLE
deps(contrib): bump to libbpf 0.5.0

### PR DESCRIPTION
**Pull request by leodido**
This patch bumps the libbpf dependency to its v0.5.0

On top of it, it adds the changes to make it work with elftoolchain.

### CODE REVIEW

**Comment by nicholasberlin** [comment]
Please forgive my ignorance

I ran a diff between libbpf and the release of libbpf-0.5.0
```
> diff -r -u3 libbpf-0.5.0 libbpf
Only in libbpf-0.5.0: .github
Only in libbpf/include: elfdefinitions.h
Only in libbpf/include: gelf.h
Only in libbpf/include: libelf.h
Only in libbpf/include/linux: ethtool.h
Only in libbpf/include/linux: perf_event.h
Only in libbpf/include/linux: socket.h
Only in libbpf-0.5.0: .lgtm.yml
Only in libbpf-0.5.0: .readthedocs.yaml
diff -r -u3 libbpf-0.5.0/src/libbpf.c libbpf/src/libbpf.c
--- libbpf-0.5.0/src/libbpf.c	2021-09-08 19:01:51.000000000 -0400
+++ libbpf/src/libbpf.c	2021-11-15 09:51:00.087068690 -0500
@@ -4515,6 +4515,10 @@
 		close(pin_fd);
 		return err;
 	}
+
+	// close the old descriptor, otherwise we leave a dangling ref to map
+	close(pin_fd);
+
 	map->pinned = true;
 	pr_debug("reused pinned map at '%s'\n", map->pin_path);
 
diff -r -u3 libbpf-0.5.0/src/linker.c libbpf/src/linker.c
--- libbpf-0.5.0/src/linker.c	2021-09-08 19:01:51.000000000 -0400
+++ libbpf/src/linker.c	2021-11-15 09:51:00.091068735 -0500
@@ -13,7 +13,6 @@
 #include <errno.h>
 #include <linux/err.h>
 #include <linux/btf.h>
-#include <elf.h>
 #include <libelf.h>
 #include <gelf.h>
 #include <fcntl.h>
diff -r -u3 libbpf-0.5.0/src/Makefile libbpf/src/Makefile
--- libbpf-0.5.0/src/Makefile	2021-09-08 19:01:51.000000000 -0400
+++ libbpf/src/Makefile	2021-11-15 09:51:00.079068601 -0500
@@ -16,7 +16,7 @@
 TOPDIR = ..
 
 INCLUDES := -I. -I$(TOPDIR)/include -I$(TOPDIR)/include/uapi
-ALL_CFLAGS := $(INCLUDES)
+ALL_CFLAGS := $(INCLUDES) -fPIC
 
 SHARED_CFLAGS += -fPIC -fvisibility=hidden -DSHARED
 
Only in libbpf-0.5.0: .travis.yml
```

Are these files still needed? Where do they come from?
```
Only in libbpf/include: elfdefinitions.h
Only in libbpf/include: gelf.h
Only in libbpf/include: libelf.h
Only in libbpf/include/linux: ethtool.h
Only in libbpf/include/linux: perf_event.h
Only in libbpf/include/linux: socket.h
```

It seems the following were added for aarch64 support (https://github.com/elastic/ebpf/commit/17126e37286c42348c0430fe5bbb66df64705100)
```
libbpf/include: elfdefinitions.h
ibbpf/include: gelf.h
libbpf/include: libelf.h
```
And it seems the following were added to fix libbf builds (https://github.com/elastic/ebpf/commit/11471afac55db734a31804a5245e35116a9d4460)
```
Only in libbpf/include/linux: ethtool.h
Only in libbpf/include/linux: perf_event.h
Only in libbpf/include/linux: socket.h
```

**Review by nicholasberlin — APPROVED** [review]
I think I've convinced myself this is good to go, I wonder if files we added to fix things previously are still necessary, but if it works. LGTM.

**Comment by stanek-michal** [comment]
Were there any new changes necessary to make the new libbpf run with our stuff or was it enough to copy over our previous changes? (the legacy kprobe fix, kernel version setter, etc). Ideally we could have the import commit separate from the commit with our own patches (for better visibility), but if you didn't add anything new then it's fine to have a combined import+patch commit like this.

**Comment by fntlnz** [comment]
Just adding that the current toolchain we use on Jenkins does not work well with this libbpf version (leads to issues while parsing ELF binaries and there are some missing constants as well).

**Comment by stanek-michal** [comment]
> Just adding that the current toolchain we use on Jenkins does not work well with this libbpf version (leads to issues while parsing ELF binaries and there are some missing constants as well).

I'll push a PR to the toolchain soon to fix this.

**Comment by leodido** [comment]
I'll come back to this as soon other things on my plate will leave me in peace ☮️ 

But, lemme past here this link on how to fix undeclared `__NR_bpf` problem (see CI) ➡️ https://lore.kernel.org/bpf/1637804167-8323-1-git-send-email-yangtiezhu@loongson.cn/ (newer libbpf contains the fix).

**Comment by mmat11** [comment]
> ... the legacy kprobe fix ...

FYI libbpf `v0.6.0` has been released 2 days ago and it seems to implement k,uprobe attach via the debugfs API (4.17-)

https://github.com/libbpf/libbpf/releases/tag/v0.6.0
https://github.com/libbpf/libbpf/commit/749b3942a09300a570198bc27814405ab92607ae

**Pull request closed without merging**
